//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class Right: ObservableObject
    {
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Right()
        {
            this.Code = "";
            this.Name = "";
            this.Note = "";
            this.RoleRights = new HashSet<RoleRight>();
        }
    
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private string _Code;
        public string Code { get => _Code; set => Set(ref _Code, value); }
        private string _Name;
        public string Name { get => _Name; set => Set(ref _Name, value); }
        private string _Note;
        public string Note { get => _Note; set => Set(ref _Note, value); }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleRight> RoleRights { get; set; }
    }
}
