//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class RoleRight: ObservableObject
    {
     
        private int _RoleId;
        public int RoleId { get => _RoleId; set => Set(ref _RoleId, value); }
        private int _RightId;
        public int RightId { get => _RightId; set => Set(ref _RightId, value); }
    
        public virtual Right Right { get; set; }
        public virtual Role Role { get; set; }
    }
}
