//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToolMgtEntities : DbContext
    {
        public ToolMgtEntities()
            : base("name=ToolMgtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Duty> Duties { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleRight> RoleRights { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<ToolCategory> ToolCategories { get; set; }
        public virtual DbSet<ToolDamage> ToolDamages { get; set; }
        public virtual DbSet<ToolState> ToolStates { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ToolPkgItem> ToolPkgItems { get; set; }
        public virtual DbSet<ToolRecord> ToolRecords { get; set; }
        public virtual DbSet<ToolRepair> ToolRepairs { get; set; }
        public virtual DbSet<ToolPurchaseOrder> ToolPurchaseOrders { get; set; }
        public virtual DbSet<ToolPurchaseOrderDtl> ToolPurchaseOrderDtls { get; set; }
    }
}
