//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class ToolPkgItem: ObservableObject
    {
     
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private int _ParentId;
        public int ParentId { get => _ParentId; set => Set(ref _ParentId, value); }
        private int _ChildrenId;
        public int ChildrenId { get => _ChildrenId; set => Set(ref _ChildrenId, value); }
        private System.DateTime _CreateDate;
        public System.DateTime CreateDate { get => _CreateDate; set => Set(ref _CreateDate, value); }
    }
}
