//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class ToolRepair: ObservableObject
    {
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolRepair()
        {
            this.Note = "";
        }
    
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private int _ToolId;
        public int ToolId { get => _ToolId; set => Set(ref _ToolId, value); }
        private int _RepairCycle;
        public int RepairCycle { get => _RepairCycle; set => Set(ref _RepairCycle, value); }
        private int _Qty;
        public int Qty { get => _Qty; set => Set(ref _Qty, value); }
        private int _OperatorId;
        public int OperatorId { get => _OperatorId; set => Set(ref _OperatorId, value); }
        private bool _IsApprove;
        public bool IsApprove { get => _IsApprove; set => Set(ref _IsApprove, value); }
        private bool _IsComplete;
        public bool IsComplete { get => _IsComplete; set => Set(ref _IsComplete, value); }
        private System.DateTime _CreateTime;
        public System.DateTime CreateTime { get => _CreateTime; set => Set(ref _CreateTime, value); }
        private string _Note;
        public string Note { get => _Note; set => Set(ref _Note, value); }
        private int _ApproveUserId;
        public int ApproveUserId { get => _ApproveUserId; set => Set(ref _ApproveUserId, value); }
        private Nullable<System.DateTime> _ApproveDate;
        public Nullable<System.DateTime> ApproveDate { get => _ApproveDate; set => Set(ref _ApproveDate, value); }
    }
}
