//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class ToolPurchaseOrder: ObservableObject
    {
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolPurchaseOrder()
        {
            this.OrderNo = "";
            this.Note = "";
        }
    
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private string _OrderNo;
        public string OrderNo { get => _OrderNo; set => Set(ref _OrderNo, value); }
        private bool _IsApprove;
        public bool IsApprove { get => _IsApprove; set => Set(ref _IsApprove, value); }
        private int _ApproveUserId;
        public int ApproveUserId { get => _ApproveUserId; set => Set(ref _ApproveUserId, value); }
        private Nullable<System.DateTime> _ApproveDate;
        public Nullable<System.DateTime> ApproveDate { get => _ApproveDate; set => Set(ref _ApproveDate, value); }
        private int _OperatorId;
        public int OperatorId { get => _OperatorId; set => Set(ref _OperatorId, value); }
        private string _Note;
        public string Note { get => _Note; set => Set(ref _Note, value); }
    }
}
