//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class ToolPurchaseOrderDtl: ObservableObject
    {
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolPurchaseOrderDtl()
        {
            this.ToolName = "";
            this.ToolSpec = "";
            this.ToolCategoryName = "";
            this.Manufacturer = "";
            this.Note = "";
        }
    
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private int _OrderId;
        public int OrderId { get => _OrderId; set => Set(ref _OrderId, value); }
        private int _Seq;
        public int Seq { get => _Seq; set => Set(ref _Seq, value); }
        private string _ToolName;
        public string ToolName { get => _ToolName; set => Set(ref _ToolName, value); }
        private string _ToolSpec;
        public string ToolSpec { get => _ToolSpec; set => Set(ref _ToolSpec, value); }
        private string _ToolCategoryName;
        public string ToolCategoryName { get => _ToolCategoryName; set => Set(ref _ToolCategoryName, value); }
        private string _Manufacturer;
        public string Manufacturer { get => _Manufacturer; set => Set(ref _Manufacturer, value); }
        private int _Qty;
        public int Qty { get => _Qty; set => Set(ref _Qty, value); }
        private string _Note;
        public string Note { get => _Note; set => Set(ref _Note, value); }
    }
}
