//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class ToolDamage: ObservableObject
    {
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolDamage()
        {
            this.Note = "";
        }
    
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private int _ToolId;
        public int ToolId { get => _ToolId; set => Set(ref _ToolId, value); }
        private int _DamageId;
        public int DamageId { get => _DamageId; set => Set(ref _DamageId, value); }
        private System.DateTime _DamageDate;
        public System.DateTime DamageDate { get => _DamageDate; set => Set(ref _DamageDate, value); }
        private int _DutyUserId;
        public int DutyUserId { get => _DutyUserId; set => Set(ref _DutyUserId, value); }
        private int _OperatorId;
        public int OperatorId { get => _OperatorId; set => Set(ref _OperatorId, value); }
        private string _Note;
        public string Note { get => _Note; set => Set(ref _Note, value); }
    }
}
