//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class ToolRecord: ObservableObject
    {
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolRecord()
        {
            this.Note = "";
        }
    
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private int _ToolId;
        public int ToolId { get => _ToolId; set => Set(ref _ToolId, value); }
        private int _BorrowerId;
        public int BorrowerId { get => _BorrowerId; set => Set(ref _BorrowerId, value); }
        private System.DateTime _BorrowTime;
        public System.DateTime BorrowTime { get => _BorrowTime; set => Set(ref _BorrowTime, value); }
        private int _BorrowOperatorId;
        public int BorrowOperatorId { get => _BorrowOperatorId; set => Set(ref _BorrowOperatorId, value); }
        private System.DateTime _ExceptReturnTime;
        public System.DateTime ExceptReturnTime { get => _ExceptReturnTime; set => Set(ref _ExceptReturnTime, value); }
        private Nullable<System.DateTime> _RealReturnTime;
        public Nullable<System.DateTime> RealReturnTime { get => _RealReturnTime; set => Set(ref _RealReturnTime, value); }
        private int _ReturnOperatorId;
        public int ReturnOperatorId { get => _ReturnOperatorId; set => Set(ref _ReturnOperatorId, value); }
        private int _ReturnStateId;
        public int ReturnStateId { get => _ReturnStateId; set => Set(ref _ReturnStateId, value); }
        private bool _IsReturn;
        public bool IsReturn { get => _IsReturn; set => Set(ref _IsReturn, value); }
        private string _Note;
        public string Note { get => _Note; set => Set(ref _Note, value); }
    
        public virtual Tool Tool { get; set; }
    }
}
