//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    using GalaSoft.MvvmLight;
    
    public partial class User: ObservableObject
    {
     
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ImagePath = "";
            this.FaceToken = "";
        }
    
        private int _Id;
        public int Id { get => _Id; set => Set(ref _Id, value); }
        private string _Code;
        public string Code { get => _Code; set => Set(ref _Code, value); }
        private string _Name;
        public string Name { get => _Name; set => Set(ref _Name, value); }
        private string _CardNo;
        public string CardNo { get => _CardNo; set => Set(ref _CardNo, value); }
        private int _DeptId;
        public int DeptId { get => _DeptId; set => Set(ref _DeptId, value); }
        private int _DutyId;
        public int DutyId { get => _DutyId; set => Set(ref _DutyId, value); }
        private string _Pwd;
        public string Pwd { get => _Pwd; set => Set(ref _Pwd, value); }
        private string _Phone;
        public string Phone { get => _Phone; set => Set(ref _Phone, value); }
        private bool _IsDel;
        public bool IsDel { get => _IsDel; set => Set(ref _IsDel, value); }
        private string _Note;
        public string Note { get => _Note; set => Set(ref _Note, value); }
        private int _RoleId;
        public int RoleId { get => _RoleId; set => Set(ref _RoleId, value); }
        private System.DateTime _JoinDate;
        public System.DateTime JoinDate { get => _JoinDate; set => Set(ref _JoinDate, value); }
        private string _ImagePath;
        public string ImagePath { get => _ImagePath; set => Set(ref _ImagePath, value); }
        private string _FaceToken;
        public string FaceToken { get => _FaceToken; set => Set(ref _FaceToken, value); }
    }
}
